# Generated by Django 2.2.13 on 2021-09-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210922_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='selected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
