# Generated by Django 2.2.13 on 2021-09-22 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210922_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='slug',
            field=models.CharField(default='home', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_title', models.CharField(max_length=100)),
                ('google_map_location', models.CharField(max_length=1000)),
                ('about_office_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('message_title', models.CharField(max_length=1000)),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Banner')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100)),
                ('small_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('old_works_titl', models.CharField(max_length=100)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Banner')),
                ('old_works', models.ManyToManyField(to='core.Item')),
            ],
        ),
    ]
