# Generated by Django 2.2.13 on 2021-09-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210922_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
