# Generated by Django 2.2.13 on 2021-09-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210922_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='selected',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='selected',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='selected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
