# Generated by Django 2.2.13 on 2021-09-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210922_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
