# Generated by Django 2.2.13 on 2021-09-22 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_about_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='old_works_titl',
            new_name='old_works_title',
        ),
    ]
